spring.application.name=nem12-ingest-batch-service
# --- DataSource (Database Connection) ---
spring.datasource.url=jdbc:postgresql://localhost:54332/mydb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=passadmin

# --- JPA / Hibernate Settings ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Spring Batch Metadata Tables ---
spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false

# --- nem12 ingest properties ---
flo.nem12.ingest.archive.target=file-system-local
flo.nem12.ingest.archive.file-system-local.location=./ingest
flo.nem12.ingest.staging.location=

flo.nem12.ingest.chunk-size=100
flo.nem12.ingest.line.delimiter=,

flo.nem12.meter-reading.commit.chunk-size=${flo.nem12.ingest.chunk-size}

flo.nem12.ingest.job.name=ingestJob
flo.nem12.ingest.step.name=ingestStep
flo.nem12.meter-reading.commit.step.name=commitMeterReadingStep